oauth2:
  password:
    auth:
      url: http://localhost:8080/authenticate
  resources:
    -
      path: "mypath"
      target: "mytarget"
    -
      path: "/mypath"
      target: "mytarget"
    -
      path: "/todos"
      target: "http://localhost:8080/todos"